Repository ChaoticOnyx/OnyxBay14, pull requests merged in 2022-11, with the labels that each got.

#75 feat: add localization label
  .github/labeler.yml
Labels: :musical_note: Без C#

#74 Trans-лейт
  Content.Client/Changelog/ChangelogWindow.xaml
  Content.Client/Changelog/ChangelogWindow.xaml.cs
  Content.Client/Preferences/UI/HumanoidProfileEditor.xaml
  Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
  Resources/Locale/en-US/reagents/norepinephricacid.ftl
  Resources/Locale/ru-RU/body-types.ftl
  Resources/Locale/ru-RU/changelog/changelog-window.ftl
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
  Resources/Locale/ru-RU/game-ticking/game-ticker.ftl
  Resources/Locale/ru-RU/info/server-info.ftl
  Resources/Locale/ru-RU/lobby/lobby-gui.ftl
  Resources/Locale/ru-RU/lobby/lobby-state.ftl
  Resources/Locale/ru-RU/lobby/ui/lobby-character-preview-panel.ftl
  Resources/Locale/ru-RU/lobby/ui/observe-warning-window.ftl
  Resources/Locale/ru-RU/main-menu/main-menu.ftl
  Resources/Locale/ru-RU/preferences/ui/humanoid-profile-editor.ftl
  Resources/Locale/ru-RU/reagents/norepinephricacid.ftl
  Resources/Locale/ru-RU/species/species.ftl
  Resources/Locale/ru-RU/voting/ui/vote-call-menu-button.ftl
  Resources/Prototypes/Traits/disabilities.yml
Labels: :iphone: UX/UI, :ru: локализация

#77 tweak: add music and a bit of translation
  Resources/Audio/Lobby/anyone_who_knows_what_love_is.ogg
  Resources/Audio/Lobby/i_have_a_dream.ogg
  Resources/Audio/Lobby/sandman.ogg
  Resources/Audio/Lobby/the_end_of_the_world.ogg
  Resources/Audio/Lobby/the_man_who_sold_the_world.ogg
  Resources/Locale/ru-RU/access/components/id-examinable-component.ftl
  Resources/Locale/ru-RU/cable/cable-multitool-system.ftl
  Resources/Locale/ru-RU/chat/ui/chat-box.ftl
  Resources/Locale/ru-RU/construction/components/construction-component-verbs.ftl
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
  Resources/Locale/ru-RU/examine/examine-system.ftl
  Resources/Locale/ru-RU/health-examinable/health-examinable-comp.ftl
  Resources/Locale/ru-RU/pointing/pointing-verb.ftl
  Resources/Locale/ru-RU/pulling/pullable-component.ftl
  Resources/Locale/ru-RU/verbs/verb-system.ftl
  Resources/Prototypes/SoundCollections/lobby.yml
Labels: :musical_note: Без C#, :ru: локализация

#81 update: readme and logo
  README.md
  Resources/Textures/Logo/logo.png
  Resources/Textures/Logo/logo.svg
Labels: :musical_note: Без C#

#84 update: xiv
  Resources/Textures/Logo/logo.png
Labels: :musical_note: Без C#

#90 fix: helmet overlays
  Content.Client/Clothing/HelmetOverlaySystem.cs
  Content.Server/Clothing/Systems/HelmetOverlaySystem.cs
  Content.Shared/Clothing/EntitySystems/SharedHelmetOverlaySystem.cs
Labels: Чейнджлог: :white_check_mark:, :wrench: фикс

#91 tweak: remove sex restrictions from body types
  Resources/Prototypes/BodyTypes/normal.yml
  Resources/Prototypes/BodyTypes/slim.yml
Labels: :musical_note: Без C#, Чейнджлог: :white_check_mark:

#95 feat: add restart after round end command
  Content.Server/ServerUpdates/RestartOnRoundEndCommand.cs
  Content.Server/ServerUpdates/ServerUpdateManager.cs
  Resources/Locale/ru-RU/RobustToolbox/commands.ftl
Labels: :gear: кнопки, 🔩 улучшение, :ru: локализация

#96 Overmap
  Content.Client/Entry/EntryPoint.cs
  Content.Client/Overmap/OvermapNavigatorSystem.cs
  Content.Client/Overmap/OvermapSystem.cs
  Content.Client/Shuttles/BUI/ShuttleConsoleBoundUserInterface.cs
  Content.Client/Shuttles/UI/NavigatorControl.cs
  Content.Client/Shuttles/UI/OvermapTab.xaml
  Content.Client/Shuttles/UI/OvermapTab.xaml.cs
  Content.Client/Shuttles/UI/RadarTab.xaml
  Content.Client/Shuttles/UI/RadarTab.xaml.cs
  Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
  Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
  Content.IntegrationTests/Tests/ShuttleTest.cs
  Content.IntegrationTests/Tests/Shuttles/BluespaceTest.cs
  Content.IntegrationTests/Tests/Shuttles/ShuttleTest.cs
  Content.Server/Overmap/OvermapObjectComponent.cs
  Content.Server/Overmap/OvermapTile.cs
  Content.Server/Overmap/Prototypes/OvermapLayerContentPrototype.cs
  Content.Server/Overmap/Prototypes/OvermapLayerPrototype.cs
  Content.Server/Overmap/Prototypes/OvermapPresetPrototype.cs
  Content.Server/Overmap/Systems/OvermapGenerator.cs
  Content.Server/Overmap/Systems/OvermapNavigatorSystem.cs
  Content.Server/Overmap/Systems/OvermapSystem.cs
  Content.Server/Shuttles/Components/BluespaceComponent.cs
  Content.Server/Shuttles/Components/FTLComponent.cs
  Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.Bluespace.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.cs
  Content.Shared/CCVar/CCVars.cs
  Content.Shared/Overmap/OvermapPointState.cs
  Content.Shared/Overmap/SharedOvermapNavigatorSystem.cs
  Content.Shared/Overmap/SharedOvermapSystem.cs
  Content.Shared/Shuttles/BUIStates/OvermapNavigatorBoundInterfaceState.cs
  Content.Shared/Shuttles/BUIStates/ShuttleConsoleBoundInterfaceState.cs
  Content.Shared/Shuttles/BUIStates/ShuttleNavigatorRadarBoundInterfaceState.cs
  Content.Shared/Shuttles/Components/SharedOvermapNavigatorComponent.cs
  Content.Shared/Shuttles/Events/EnterBluespaceMessage.cs
  Content.Shared/Shuttles/Events/ExitBluespaceMessage.cs
  Content.Shared/Shuttles/Systems/SharedShuttleConsoleSystem.cs
  Content.Shared/Shuttles/Systems/SharedShuttleSystem.cs
  Resources/Locale/ru-RU/shuttles/console.ftl
  Resources/Maps/Salvage/ruin-cargo-salvage.yml
  Resources/Maps/Salvage/small-a-2.yml
  Resources/Maps/Salvage/small-a-3.yml
  Resources/Maps/Salvage/small-a-4.yml
  Resources/Maps/infiltrator.yml
  Resources/Maps/nukieplanet.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Maps/salvage.yml
  Resources/Prototypes/Maps/sevastopol.yml
  Resources/Prototypes/Overmap/content.yml
  Resources/Prototypes/Overmap/layers.yml
  Resources/Prototypes/Overmap/presets.yml
  Resources/Prototypes/Parallaxes/default.yml
  Resources/Textures/Parallaxes/bluespace.png
Labels: 🗺️ карта, Чейнджлог: :white_check_mark:, 🔩 улучшение, :iphone: UX/UI, :robot: Тесты, :ru: локализация

#100 tweak: don't kick player after ban
  Content.Server/Administration/Commands/BanCommand.cs
Labels: :gear: кнопки

#101 add: slim shoes sprites
  Resources/Textures/Clothing/Shoes/Boots/combatboots.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/combatboots.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Boots/jackboots.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/jackboots.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Boots/laceups.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/laceups.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Boots/magboots-advanced.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/magboots-advanced.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Boots/magboots-advanced.rsi/on-equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/magboots-syndicate.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/magboots-syndicate.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Boots/magboots-syndicate.rsi/on-equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/magboots.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/magboots.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Boots/magboots.rsi/on-equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/workboots.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Boots/workboots.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Color/black.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Color/black.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Color/blue.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Color/blue.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Color/brown.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Color/brown.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Color/green.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Color/green.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Color/orange.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Color/orange.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Color/purple.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Color/purple.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Color/red.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Color/red.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Color/white.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Color/white.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Color/yellow.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Color/yellow.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Misc/flippers.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Misc/flippers.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Misc/leather.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Misc/leather.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Misc/slippers.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Misc/slippers.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Misc/tourist.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Misc/tourist.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Specific/chef.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Specific/chef.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Specific/clown.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Specific/clown.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Specific/cult.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Specific/cult.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Specific/galoshes.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Specific/galoshes.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Specific/spaceninja.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Specific/spaceninja.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Specific/swat.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Specific/swat.rsi/meta.json
  Resources/Textures/Clothing/Shoes/Specific/wizard.rsi/equipped-FEET-HumanSlim.png
  Resources/Textures/Clothing/Shoes/Specific/wizard.rsi/meta.json
Labels: :musical_note: Без C#, 🎨 спрайты, Чейнджлог: :white_check_mark:

#102 remove: cringe mode from voting
  Resources/Prototypes/game_presets.yml
Labels: :musical_note: Без C#

#104 fix: shaders on OpenGL ES 3.0
  Resources/Prototypes/Shaders/shaders.yml
  Resources/Textures/Shaders/crt.swsl
  Resources/Textures/Shaders/crt2.swsl
Labels: :musical_note: Без C#, :wrench: фикс

#107 tweak: add more tanks to dispensers and remove locks
  Resources/Prototypes/Catalog/VendingMachines/Inventories/tankdispenser.yml
  Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
Labels: :musical_note: Без C#, Чейнджлог: :white_check_mark:

#109 fix: more localization
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
Labels: :musical_note: Без C#, :wrench: фикс, :ru: локализация

#111 tweak: improve ban notification
  Content.Client/Credits/CreditsWindow.xaml.cs
  Content.Client/Info/DevInfoBanner.cs
  Content.Client/Info/LinkBanner.cs
  Content.Client/Info/ServerInfo.cs
  Content.Client/Links/UILinks.cs
  Content.Client/UserInterface/Systems/EscapeMenu/EscapeUIController.cs
  Content.Server/Administration/Commands/BanCommand.cs
  Content.Server/Database/ServerBanDef.cs
  Content.Shared/Links/Links.cs
  Resources/Locale/ru-RU/connection-messages.ftl
Labels: :iphone: UX/UI, :ru: локализация

#112 feat: add more discord webhooks
  Content.Server/Administration/Commands/BanCommand.cs
  Content.Server/Administration/Commands/PardonCommand.cs
  Content.Server/Administration/Systems/BwoinkSystem.cs
  Content.Server/Chat/Managers/ChatManager.cs
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Server/DiscordWebhooks/DiscordModels.cs
  Content.Server/DiscordWebhooks/DiscordWebhooksManager.cs
  Content.Server/DiscordWebhooks/RoundEndReporterSystem.cs
  Content.Server/DiscordWebhooks/Webhooks/BanMessageDiscordWebhook.cs
  Content.Server/DiscordWebhooks/Webhooks/EmoteMessageDiscordWebhook.cs
  Content.Server/DiscordWebhooks/Webhooks/GenericMessageDiscordWebhook.cs
  Content.Server/DiscordWebhooks/Webhooks/OOCMessageDiscordWebhook.cs
  Content.Server/DiscordWebhooks/Webhooks/PardonMessageDiscordWebhook.cs
  Content.Server/DiscordWebhooks/Webhooks/RoundEndMessageDiscordWebhook.cs
  Content.Server/GameTicking/GameTicker.RoundFlow.cs
  Content.Server/IoC/ServerContentIoC.cs
  Content.Server/MoMMI/IMoMMILink.cs
  Content.Server/MoMMI/MoMMILink.cs
  Content.Shared/CCVar/CCVars.cs
Labels: 🔩 улучшение

#113 fix: ban webhook
  Content.Server/Administration/Commands/BanCommand.cs
  Content.Server/Administration/Commands/PardonCommand.cs
Labels: :wrench: фикс

#114 tweak: webhooks and working mentions
  Content.Server/Administration/Commands/BanCommand.cs
  Content.Server/Administration/Commands/PardonCommand.cs
  Content.Server/Administration/Commands/RoleUnbanCommand.cs
  Content.Server/Administration/Managers/RoleBanManager.cs
  Content.Server/Chat/Managers/ChatManager.cs
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Server/DiscordWebhooks/DiscordModels.cs
  Content.Server/DiscordWebhooks/DiscordWebhooksManager.cs
  Content.Server/DiscordWebhooks/RoundEndReporterSystem.cs
  Content.Server/DiscordWebhooks/Webhooks/EmoteMessageDiscordWebhook.cs
  Content.Server/DiscordWebhooks/Webhooks/GenericMessageDiscordWebhook.cs
  Content.Server/DiscordWebhooks/Webhooks/OOCMessageDiscordWebhook.cs
  Content.Server/DiscordWebhooks/Webhooks/RoundEndMessageDiscordWebhook.cs
Labels: :wrench: фикс

#116 refact: overmap, bluespace and shuttle systems. Part I
  Content.Client/Bluespace/BluespaceSystem.cs
  Content.Client/Overmap/OvermapSystem.cs
  Content.Client/Overmap/Systems/OvermapNavigatorSystem.cs
  Content.Client/Shuttles/UI/NavigatorControl.cs
  Content.Client/Shuttles/UI/OvermapTab.xaml.cs
  Content.IntegrationTests/Tests/Shuttles/BluespaceTest.cs
  Content.Server/Administration/Commands/PardonCommand.cs
  Content.Server/Bluespace/BluespaceSystem.cs
  Content.Server/Bluespace/Events/AfterEnterBluespaceEvent.cs
  Content.Server/Bluespace/Events/AfterExitBluespaceEvent.cs
  Content.Server/Bluespace/Events/AttemptEnterBluespaceEvent.cs
  Content.Server/Bluespace/Events/AttemptExitBluespaceEvent.cs
  Content.Server/Bluespace/Events/BeforeEnterBluespaceEvent.cs
  Content.Server/Bluespace/Events/BeforeExitBluespaceEvent.cs
  Content.Server/Bluespace/Events/EnterBluespaceEvent.cs
  Content.Server/Bluespace/Events/ExitBluespaceEvent.cs
  Content.Server/BluespaceOvermapTransition/BluespaceOvermapTransitionSystem.cs
  Content.Server/Overmap/Systems/OvermapGenerator.cs
  Content.Server/Overmap/Systems/OvermapNavigatorSystem.cs
  Content.Server/Overmap/Systems/OvermapSystem.cs
  Content.Server/Shuttles/Components/BluespaceComponent.cs
  Content.Server/Shuttles/Components/ShuttleComponent.cs
  Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.Bluespace.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.cs
  Content.Shared/Bluespace/BluespaceComponent.cs
  Content.Shared/Bluespace/Events/BluespaceMapUpdatedEvent.cs
  Content.Shared/Bluespace/SharedBluespaceSystem.cs
  Content.Shared/Content.Shared.csproj
  Content.Shared/Overmap/Systems/SharedOvermapNavigatorSystem.cs
  Content.Shared/Overmap/Systems/SharedOvermapSystem.cs
  Content.Shared/Shuttles/BUIStates/OvermapNavigatorBoundInterfaceState.cs
  Content.Shared/Shuttles/Components/SharedOvermapNavigatorComponent.cs
  Content.Shared/Shuttles/Systems/SharedShuttleSystem.cs
  Resources/Locale/ru-RU/bluespace/bluespace.ftl
  Resources/Locale/ru-RU/console.ftl
Labels: 🔨 рефакторинг, :iphone: UX/UI, :robot: Тесты, :ru: локализация

#118 add: rules button to escape menu
  Content.Client/Options/UI/EscapeMenu.xaml
  Content.Client/UserInterface/Systems/EscapeMenu/EscapeUIController.cs
Labels: :iphone: UX/UI

#122 fix: round end webhook, use current connected players count
  Content.Server/DiscordWebhooks/RoundEndReporterSystem.cs
Labels: :wrench: фикс

#123 feat(channels-color): port colors from ss13
  Resources/Prototypes/radio_channels.yml
Labels: :musical_note: Без C#, Чейнджлог: :white_check_mark:

#129 tweak: add OvermapPausingSystem
  Content.Server/BluespaceOvermapTransition/BluespaceOvermapTransitionSystem.cs
  Content.Server/Overmap/OvermapTiles.cs
  Content.Server/Overmap/Systems/OvermapNavigatorSystem.cs
  Content.Server/Overmap/Systems/OvermapPausingSystem.cs
  Content.Server/Overmap/Systems/OvermapSystem.cs
Labels: 🔧 оптимизация

#130 fix: hard reset
  Content.Server/ServerUpdates/ServerUpdateManager.cs
  Content.Shared/CCVar/CCVars.cs
Labels: :wrench: фикс
