Repository ChaoticOnyx/OnyxBay14, pull requests merged in 2022-10, with the labels that each got.

#2 add: frontier map
  Resources/Maps/frontier.yml
  Resources/Prototypes/Maps/frontier.yml
Labels: No C#, Changes: Map

#4 tweak: remove cron from `publish` workflow task
  .github/workflows/publish.yml
Labels: No C#

#5 fix: arrival shuttles is now part of the station, fix medbay windoors
  Resources/Maps/frontier.yml
Labels: No C#, Changes: Map

#8 tweak: add salvage magnet to frontier, shuttle console fixes
  Content.Client/Shuttles/Systems/ShuttleConsoleSystem.cs
  Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
  Content.Shared/Shuttles/Components/RadarConsoleComponent.cs
  Resources/Maps/frontier.yml
Labels: Changes: Map

#11 tweak: remove owners
  .github/CODEOWNERS
Labels: No C#

#14 remove: remove non-orthodox maps
  Resources/Maps/bagel.yml
  Resources/Maps/lighthouse.yml
  Resources/Maps/marathon.yml
  Resources/Maps/meta.yml
  Resources/Maps/omega.yml
  Resources/Maps/packed.yml
  Resources/Maps/pillar.yml
  Resources/Maps/saltern.yml
  Resources/Maps/split.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/lighthouse.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/packed.yml
  Resources/Prototypes/Maps/pillar.yml
  Resources/Prototypes/Maps/saltern.yml
  Resources/Prototypes/Maps/split.yml
Labels: No C#, Changes: Map

#22 fix: remove minPlayers for box map
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/frontier.yml
Labels: No C#, Changes: Map

#26 Grafonium
  Content.Client/Audio/UIAudioManager.cs
  Content.Client/Changelog/ChangelogButton.cs
  Content.Client/Entry/EntryPoint.cs
  Content.Client/IoC/ClientContentIoC.cs
  Content.Client/Launcher/LauncherConnectingGui.xaml
  Content.Client/MainMenu/BackgroundControl.cs
  Content.Client/MainMenu/MainMenu.cs
  Content.Client/MainMenu/UI/MainMenuControl.xaml
  Content.Client/MainMenu/UI/MainMenuControl.xaml.cs
  Content.Client/Options/UI/Tabs/AudioTab.xaml
  Content.Client/Options/UI/Tabs/AudioTab.xaml.cs
  Content.Client/Overlays/GrainOverlay.cs
  Content.Client/Parallax/ParallaxControl.cs
  Content.Client/Reflection/ReflectionExtensions.cs
  Content.Client/Stylesheets/StyleBase.cs
  Content.Client/Stylesheets/StyleNano.cs
  Content.Client/Stylesheets/StyleSpace.cs
  Content.Client/Stylesheets/StylesheetManager.cs
  Content.Client/SurveillanceCamera/UI/SurveillanceCameraMonitorViewport.cs
  Content.Client/SurveillanceCamera/UI/SurveillanceCameraMonitorWindow.xaml
  Content.Client/UserInterface/Controls/CommonButton.cs
  Content.Client/UserInterface/Controls/FancyWindow.xaml.cs
  Content.Client/Viewport/ScalingViewport.cs
  Content.IntegrationTests/Content.IntegrationTests.csproj
  Content.Shared/CCVar/CCVars.cs
  Resources/Audio/UI/hover.ogg
  Resources/Audio/UI/main_menu_ambient.ogg
  Resources/Audio/UI/pressed.ogg
  Resources/Fonts/Exo2/Exo2 Black.ttf
  Resources/Fonts/Exo2/Exo2 BlackItalic.ttf
  Resources/Fonts/Exo2/Exo2 Bold.ttf
  Resources/Fonts/Exo2/Exo2 BoldItalic.ttf
  Resources/Fonts/Exo2/Exo2 ExtraBold.ttf
  Resources/Fonts/Exo2/Exo2 ExtraBoldItalic.ttf
  Resources/Fonts/Exo2/Exo2 ExtraLight.ttf
  Resources/Fonts/Exo2/Exo2 ExtraLightItalic.ttf
  Resources/Fonts/Exo2/Exo2 Italic.ttf
  Resources/Fonts/Exo2/Exo2 Light.ttf
  Resources/Fonts/Exo2/Exo2 LightItalic.ttf
  Resources/Fonts/Exo2/Exo2 Medium.ttf
  Resources/Fonts/Exo2/Exo2 MediumItalic.ttf
  Resources/Fonts/Exo2/Exo2 Regular.ttf
  Resources/Fonts/Exo2/Exo2 SemiBold.ttf
  Resources/Fonts/Exo2/Exo2 SemiBoldItalic.ttf
  Resources/Fonts/Exo2/Exo2 Thin.ttf
  Resources/Fonts/Exo2/Exo2 ThinItalic.ttf
  Resources/Locale/ru-RU/changelog/changelog-window.ftl
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
  Resources/Locale/ru-RU/main-menu/main-menu.ftl
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Misc/fluff_lights.yml
  Resources/Prototypes/Entities/Objects/Power/lights.yml
  Resources/Prototypes/Shaders/shaders.yml
  Resources/Textures/Shaders/crt.swsl
  Resources/Textures/Shaders/grain.swsl
  Resources/Textures/main_menu_background.png
Labels: Changes: UI

#31 Some sprite and visual improvments
  Resources/Prototypes/Entities/Objects/Power/lights.yml
  Resources/Prototypes/Entities/Structures/Doors/Shutter/blast_door.yml
  Resources/Prototypes/Entities/Structures/Lighting/base_lighting.yml
  Resources/Prototypes/Entities/Structures/Walls/walls.yml
  Resources/Prototypes/Maps/frontier.yml
  Resources/Textures/Structures/Doors/Shutters/blastdoor.rsi/closed.png
  Resources/Textures/Structures/Doors/Shutters/blastdoor.rsi/closing.png
  Resources/Textures/Structures/Doors/Shutters/blastdoor.rsi/meta.json
  Resources/Textures/Structures/Doors/Shutters/blastdoor.rsi/open.png
  Resources/Textures/Structures/Doors/Shutters/blastdoor.rsi/opening.png
  Resources/Textures/Structures/Walls/solid.rsi/full.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over0.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over1.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over2.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over3.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over4.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over5.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over6.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over7.png
  Resources/Textures/Structures/Walls/solid.rsi/rgeneric.png
  Resources/Textures/Structures/Walls/solid.rsi/solid0.png
  Resources/Textures/Structures/Walls/solid.rsi/solid1.png
  Resources/Textures/Structures/Walls/solid.rsi/solid2.png
  Resources/Textures/Structures/Walls/solid.rsi/solid3.png
  Resources/Textures/Structures/Walls/solid.rsi/solid4.png
  Resources/Textures/Structures/Walls/solid.rsi/solid5.png
  Resources/Textures/Structures/Walls/solid.rsi/solid6.png
  Resources/Textures/Structures/Walls/solid.rsi/solid7.png
  Resources/Textures/Structures/Walls/solidrust.rsi/full.png
  Resources/Textures/Structures/Walls/solidrust.rsi/rust.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust0.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust1.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust2.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust3.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust4.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust5.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust6.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust7.png
  Resources/Textures/Structures/Windows/directional.rsi/window.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/full.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow0.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow1.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow3.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow4.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow5.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow6.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow7.png
  Resources/Textures/Structures/Windows/window.rsi/full.png
  Resources/Textures/Structures/Windows/window.rsi/window0.png
  Resources/Textures/Structures/Windows/window.rsi/window1.png
  Resources/Textures/Structures/Windows/window.rsi/window2.png
  Resources/Textures/Structures/Windows/window.rsi/window3.png
  Resources/Textures/Structures/Windows/window.rsi/window4.png
  Resources/Textures/Structures/Windows/window.rsi/window5.png
  Resources/Textures/Structures/Windows/window.rsi/window6.png
  Resources/Textures/Structures/Windows/window.rsi/window7.png
  Resources/Textures/Tiles/plating.png
Labels: No C#, Changes: Map, Changes: Sprites, Status: Needs Review

#38 tweak: disable slimes and reptilians
  Resources/Prototypes/Species/reptilian.yml
  Resources/Prototypes/Species/slime.yml
Labels: No C#

#39 tweak: untie sex and sprites
  Content.Client/Humanoid/HumanoidVisualizerSystem.cs
  Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
  Content.Shared/Humanoid/HumanoidVisualLayersExtension.cs
  Resources/Locale/ru-RU/body-types.ftl
  Resources/Prototypes/BodyTypes/normal.yml
  Resources/Prototypes/BodyTypes/slim.yml
  Resources/Prototypes/Species/human.yml
  Resources/Textures/Mobs/Species/Human/parts.rsi/head.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/head_f.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/head_m.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/head_slim.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/l_arm.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/l_foot.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/l_hand.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/l_leg.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/meta.json
  Resources/Textures/Mobs/Species/Human/parts.rsi/r_arm.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/r_foot.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/r_hand.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/r_leg.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/torso.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/torso_f.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/torso_m.png
  Resources/Textures/Mobs/Species/Human/parts.rsi/torso_slim.png
Labels: Changes: UI, Changes: Sprites

#41 tweak: add a way to play without RTX
  Content.Client/Clothing/Overlays/HelmetOverlay.cs
  Content.Client/MainMenu/BackgroundControl.cs
  Content.Client/Options/UI/Tabs/GraphicsTab.xaml
  Content.Client/Options/UI/Tabs/GraphicsTab.xaml.cs
  Content.Client/Overlays/GrainOverlay.cs
  Content.Client/SurveillanceCamera/UI/SurveillanceCameraMonitorViewport.cs
  Content.Shared/CCVar/CCVars.cs
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
Labels: Changes: UI

#48 port: more clothing for slim
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/blue.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/blue.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/blue.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/brown.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/brown.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/brown.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/darkblue.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/darkblue.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/darkblue.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/darkgreen.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/darkgreen.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/darkgreen.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/green.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/green.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/green.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/grey.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/grey.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/grey.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/lightbrown.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/lightbrown.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/lightbrown.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/lightpurple.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/lightpurple.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/lightpurple.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/maroon.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/maroon.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/maroon.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/orange.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/orange.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/orange.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/pink.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/pink.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/pink.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/red.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/red.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/red.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/teal.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/teal.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/teal.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/yellow.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/yellow.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/Color/yellow.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/scientist.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/scientist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/scientist.rsi/meta.json
Labels: :musical_note: Без C#, 🎨 спрайты, Чейнджлог: :white_check_mark:

#49 revert: new localization bugs
  Content.Client/Administration/UI/Tabs/AdminTab/AdminShuttleWindow.xaml.cs
  Content.Server/Administration/Commands/ShuttleCommands.cs
  Content.Shared/Entry/EntryPoint.cs
  Content.Shared/IoC/SharedContentIoC.cs
  Content.Shared/Localizations/Localization.cs
  Resources/Locale/ru-RU/_lib.ftl
Labels: :iphone: UX/UI

#51 port: tech floors from onyxbay
  Resources/Locale/ru-RU/tiles/tiles.ftl
  Resources/Prototypes/Entities/Objects/Misc/tiles.yml
  Resources/Prototypes/Stacks/floor_tile_stacks.yml
  Resources/Prototypes/Tiles/floors.yml
  Resources/Textures/Objects/Tiles/tile.rsi/meta.json
  Resources/Textures/Objects/Tiles/tile.rsi/techfloor.png
  Resources/Textures/Objects/Tiles/tile.rsi/techgrid.png
  Resources/Textures/Objects/Tiles/tile.rsi/techmaint.png
  Resources/Textures/Objects/Tiles/tile.rsi/techridge.png
  Resources/Textures/Tiles/tech_floor.png
  Resources/Textures/Tiles/tech_grid.png
  Resources/Textures/Tiles/tech_maint.png
  Resources/Textures/Tiles/tech_ridge.png
Labels: :musical_note: Без C#, 🎨 спрайты, Чейнджлог: :white_check_mark:

#54 add: sprites for the rest of the jobs
  Resources/Prototypes/Catalog/VendingMachines/Inventories/bardrobe.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Textures/Clothing/Uniforms/Jumpsuit/bartender.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/bartender.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/bartender_purple.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/bartender_purple.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/bartender_purple.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/hydro.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/hydro.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/librarian.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/librarian.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/librarian.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/librarian.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/librarian.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/librarian.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/medical.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/medical.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/medical.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/medical.rsi/meta.json
Labels: :musical_note: Без C#, 🎨 спрайты, Чейнджлог: :white_check_mark:

#55 fix: rotate tile's sprite
  Resources/Textures/Tiles/tech_maint.png
Labels: :musical_note: Без C#

#57 port: chair sprites
  Resources/Textures/Structures/Furniture/chairs.rsi/chair-greyscale-knocked.png
  Resources/Textures/Structures/Furniture/chairs.rsi/chair-greyscale.png
  Resources/Textures/Structures/Furniture/chairs.rsi/chair-knocked.png
  Resources/Textures/Structures/Furniture/chairs.rsi/chair.png
Labels: :musical_note: Без C#, 🎨 спрайты

#60 fix: salvage's jumpsuit sprites
  Resources/Textures/Clothing/Uniforms/Jumpsuit/salvage.rsi/equipped-INNERCLOTHING-HumanSlim.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/salvage.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/salvage.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/salvage.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/salvage.rsi/meta.json
Labels: :musical_note: Без C#, 🎨 спрайты

#61 fix: convert stereo sounds to mono
  Resources/Audio/Ambience/Objects/engine_hum.ogg
  Resources/Audio/Ambience/Objects/gravity_gen_hum.ogg
Labels: :musical_note: Без C#

#67 add: a lot of tweaks
  Content.Shared/CCVar/CCVars.cs
  Resources/Audio/Announcements/aliens.ogg
  Resources/Audio/Announcements/announce.ogg
  Resources/Audio/Announcements/attention.ogg
  Resources/Audio/Announcements/gas_leak.ogg
  Resources/Audio/Announcements/license.txt
  Resources/Audio/Announcements/meteors.ogg
  Resources/Audio/Announcements/outbreak.ogg
  Resources/Audio/Announcements/outbreak7.ogg
  Resources/Audio/Announcements/power_off.ogg
  Resources/Audio/Announcements/power_on.ogg
  Resources/Audio/Announcements/radiation.ogg
  Resources/Audio/Announcements/shuttle_dock.ogg
  Resources/Audio/Announcements/shuttlecalled.ogg
  Resources/Audio/Announcements/shuttlerecalled.ogg
  Resources/Audio/Announcements/vent_clog.ogg
  Resources/Audio/Announcements/welcome.ogg
  Resources/Audio/Lobby/crokett_39_s_theme.ogg
  Resources/Audio/Lobby/delirium.ogg
  Resources/Audio/Lobby/echoes.ogg
  Resources/Audio/Lobby/end.ogg
  Resources/Audio/Lobby/magicfly.ogg
  Resources/Audio/Lobby/space.ogg
  Resources/Audio/Lobby/space_oddity.ogg
  Resources/Audio/Lobby/title1.ogg
  Resources/Audio/Lobby/title2.ogg
  Resources/Prototypes/Entities/Objects/Power/lights.yml
  Resources/Prototypes/Entities/Structures/Lighting/base_lighting.yml
  Resources/Prototypes/Entities/Structures/Shuttles/thrusters.yml
  Resources/Prototypes/Entities/Structures/Specific/cryo.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/Signs/bar_sign.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/sevastopol.yml
  Resources/Prototypes/Parallaxes/default.yml
  Resources/Prototypes/SoundCollections/lobby.yml
  Resources/Prototypes/lobbyscreens.yml
  Resources/Prototypes/round_announcements.yml
  Resources/Textures/LobbyScreens/attributions.yml
  Resources/Textures/LobbyScreens/indigo.png
  Resources/Textures/LobbyScreens/indigo.png.yml
  Resources/Textures/LobbyScreens/pharmacy.png
  Resources/Textures/LobbyScreens/pharmacy.png.yml
  Resources/Textures/LobbyScreens/robotics.png
  Resources/Textures/LobbyScreens/robotics.png.yml
  Resources/Textures/LobbyScreens/supermatter.png
  Resources/Textures/LobbyScreens/supermatter.png.yml
  Resources/Textures/LobbyScreens/warden.png
  Resources/Textures/LobbyScreens/warden.png.yml
  Resources/Textures/Parallaxes/layer1.png
  Resources/Textures/Parallaxes/planet.png
  Resources/Textures/Structures/Specific/cryo.rsi/icon.png
  Resources/Textures/Structures/Specific/cryo.rsi/meta.json
Labels: 🗺️ карта, 🎨 спрайты, Чейнджлог: :white_check_mark:

#68 tweak: rad collectors
  Content.Client/Singularity/Components/RadiationCollectorVisualsComponent.cs
  Content.Client/Singularity/Visualizers/RadiationCollectorVisualizer.cs
  Content.Client/Singularity/Visualizers/RadiationCollectorVisualizerSystem.cs
  Content.Server/Singularity/Components/RadiationCollectorComponent.cs
  Content.Server/Singularity/EntitySystems/RadiationCollectorSystem.cs
  Content.Shared/Singularity/Components/SharedRadiationCollectorComponent.cs
  Resources/Locale/ru-RU/_lib.ftl
  Resources/Locale/ru-RU/singularity/components/radiation-collector-component.ftl
  Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/collector.yml
  Resources/Textures/Structures/Power/Generation/Singularity/collector.rsi/ca_active.png
  Resources/Textures/Structures/Power/Generation/Singularity/collector.rsi/ca_deactive.png
  Resources/Textures/Structures/Power/Generation/Singularity/collector.rsi/ca_inactive.png
  Resources/Textures/Structures/Power/Generation/Singularity/collector.rsi/ca_off.png
  Resources/Textures/Structures/Power/Generation/Singularity/collector.rsi/ca_on.png
  Resources/Textures/Structures/Power/Generation/Singularity/collector.rsi/meta.json
  Resources/Textures/Structures/Power/Generation/Singularity/collector.rsi/tank.png
Labels: 🗺️ карта, 🎨 спрайты, Чейнджлог: :white_check_mark:, 🔩 порт

#69 add: radiation collector tests
  .github/labeler.yml
  Content.IntegrationTests/Tests/Singularity/RadiationCollectorTest.cs
  Content.Server/Singularity/Components/RadiationCollectorComponent.cs
  Content.Server/Singularity/EntitySystems/RadiationCollectorSystem.cs
  Resources/Prototypes/Catalog/Cargo/cargo_engines.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/collector.yml
Labels: :robot: Тесты

#70 tweak: parallax
  Resources/Prototypes/Parallaxes/default.yml
Labels: :musical_note: Без C#

#72 fix: damage overlay
  Content.Client/MobState/Overlays/DamageOverlay.cs
Labels: :wrench: фикс
